// if nodejs is not there, remote into jenkins container and install it:
//   docker exec -it -u root jenkins bash
//   addgroup jenkins docker
//   apt add nodejs
node {
  def commit_id
  stage('Preparation') {
    checkout scm
    sh "git rev-parse --short HEAD > .git/commit-id"                        
    commit_id = readFile('.git/commit-id').trim()
  }
  stage('test') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'npm install --only=dev'
      sh 'npm test'
    }
  }
  stage('docker build/push') {
    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
      def app = docker.build("mjheitland/docker-nodejs-demo:${commit_id}", '.').push()
    }
  }
}
