node {
  def commit_id
  stage('Preparation') {
    checkout scm
    sh "echo $PATH"
    sh "git rev-parse --short HEAD > .git/commit-id"                        
    commit_id = readFile('.git/commit-id').trim()
    sh "echo 'commit_id: ' $commit_id"
  }
  stage('test') {
    // nodejs('nodejs') {
    nodejs(nodeJSInstallationName: 'nodejs') {
      sh 'npm install --only=dev'
      sh 'npm test'
    }
  }
  stage('docker build/push') {
    docker.withRegistry('', 'dockerhub') { // connect to Dockerhub, user name + pw are stored in Jenkins under 'dockerhub'
      sh 'echo 1'
      def app = docker.build("mjheitland/docker-nodejs-demo:${commit_id}", '.').push()
      sh 'echo 2'
    }
  }
}
